### ISSUE TITLE
SSR window is not defined 

### ISSUE THREAD

**Issue by abratko** [vue-ioc/vue-ioc#20]
I have app with SSR. After i install vue-ioc via Vue.use() in app i get error 

```
ReferenceError: window is not defined
    at Object.factory (/home/abratko/webprojects/trg/whitelabel/whitelabel-vue/vsf-whitelabel-theme/node_modules/@vue-ioc/core/dist/webpack:/VueIoc/webpack/universalModuleDefinition:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18
```
Can you help to solve problem?

**Comment by gejgalis** [comment]
@abratko it looks UMD produced by webpack in vue-ioc is causing this issue. I'll try to fix today.

**Comment by gejgalis** [comment]
@abratko please try `@vue-ioc/core` version `0.2.1` and let me know if `vue-ioc` works well on SSR :)

**Comment by abratko** [comment]
It works. Thank you very much, for quickly fix.
